[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect API calls to the serverless function
[[redirects]]
  from = "/api/openai"
  to = "/.netlify/functions/openai"
  status = 200